### ISSUE TITLE
Can't install dependencies

### ISSUE THREAD

**Issue by n-rodriguez** [aanriot/django-resale#2]
Hi there!

I got this error when running `pip install -r requirements/development.txt` with Python 3.7.0 :

```sh
  Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements/development.txt (line 31)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements/development.txt (line 31))
```

**Comment by aanriot** [comment]
Hello @n-rodriguez,

As the requirements have been updated, could you retry the installation and get back to me?

Thanks.

**Comment by n-rodriguez** [comment]
Hi! It works!
Thank you!
